import React, { createContext, useContext, useState, useEffect } from 'react';

interface Language {
  code: string;
  name: string;
  nativeName: string;
}

interface LanguageContextType {
  currentLanguage: string;
  setLanguage: (language: string) => void;
  t: (key: string) => string;
  availableLanguages: Language[];
}

const languages: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ' },
];

const translations = {
  en: {
  // Login Page
  loginHeadline: 'Connecting Rural Communities to Quality Healthcare',
  loginSubheadline: 'Bridge the healthcare gap with our comprehensive telemedicine platform. Get expert consultations, digital prescriptions, and medicine availability checks from the comfort of your village.',
  loginFeatureConsult: 'Video/Audio Consultations',
  loginFeatureDelivery: 'Medicines Delivery',
  loginFeatureSupport: '24/7 Support',
  loginStatPatients: '1,250+ Active Patients',
  loginStatDoctors: '45+ Qualified Doctors',
  loginStatPharmacies: '18+ Partner Pharmacies',
  loginStatSuccess: '97.5% Success Rate',
  loginTrusted: 'Trusted by Healthcare Professionals',
  loginCompliance: 'HIPAA Compliant',
  loginEncryption: 'End-to-End Encrypted',
  loginMonitoring: '24/7 Monitoring',
  loginSignInTitle: 'Sign in to your account to TeleAsha',
  loginDashboardAccess: 'Access your healthcare dashboard',
  loginEmail: 'Email',
  loginPassword: 'Password',
  loginSignInButton: 'Sign In',
  loginNewTo: 'New to TeleAsha?',
  loginCreateAccount: 'Create New Account',
  loginAgreement: 'By signing in, you agree to our Terms of Service and Privacy Policy',
    dashboard: 'Dashboard',
    appointments: 'Appointments',
    medicines: 'Medicines',
    reports: 'Reports',
    profile: 'Profile',
    logout: 'Logout',
    overview: 'Overview',
  symptomsNav: 'Symptom Checker',
    consultations: 'Consultations',
    prescriptions: 'Prescriptions',
    inventory: 'Inventory',
    addMedicine: 'Add Medicine',
    requests: 'Requests',
    users: 'Users',
    analytics: 'Analytics',

    // Authentication
    login: 'Login',
    register: 'Register',
    forgotPassword: 'Forgot Password',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    phoneNumber: 'Phone Number',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    demoAccess: 'Demo Access',
    demoPassword: '',

    // Dashboard
    welcome: 'Welcome',
    upcomingAppointments: 'Upcoming Appointments',
    recentReports: 'Recent Reports',
    bookConsultation: 'Book Consultation',
    bookAppointment: 'Book Appointment',
    checkMedicine: 'Check Medicine',
    videoAudioCall: 'Video/Audio Call',
    findPharmacy: 'Find Pharmacy',
    healthScore: 'Health Score',
    activePrescriptions: 'Active Prescriptions',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',

    // Doctor types
    modernMedicine: 'Modern Medicine',
    countryMedicine: 'Country Medicine',
    generalMedicine: 'General Medicine',

    // Medical
  symptoms: 'Symptoms',
    fever: 'Fever',
    cough: 'Cough',
    headache: 'Headache',
    bodyPain: 'Body Pain',
    nausea: 'Nausea',
    fatigue: 'Fatigue',
    otherSymptoms: 'Other symptoms',
    checkSymptoms: 'Check Symptoms',
    symptomsRecorded: 'Symptoms Recorded',
    consultDoctor: 'Based on your symptoms, we recommend consulting a doctor. Would you like to book an appointment?',

    // Appointments
    appointmentRequests: 'Appointment Requests',
    manageAppointments: 'Manage patient appointment requests',
    approve: 'Approve',
    reject: 'Reject',
    approved: 'Approved',
    pending: 'Pending',
    rejected: 'Rejected',
    completed: 'Completed',
    startConsultation: 'Start Consultation',
    appointmentApproved: 'Appointment Approved',
    appointmentRejected: 'Appointment Rejected',
    patientNotified: 'Patient has been notified about the approved appointment.',

    // Video/Audio Calls
    videoCall: 'Video Call',
    audioCall: 'Audio Call',
    videoAudio: 'Video/Audio',
    startVideoCall: 'Start Video Call',
    startAudioCall: 'Start Audio Call',
    joinCall: 'Join Call',
    videoCallStarted: 'Video/Audio Call Started',
    connectingToPatient: 'Connecting to patient... This is a demo simulation.',
    availableForConsultations: 'Available for Consultations',
    nextConsultation: 'Next Consultation',
    videoAudioConsultations: 'Video/Audio Consultations',
    manageConsultations: 'Manage your remote consultations',
    callFeatures: 'Demo Video/Audio Call Features',
    highQualityVideoAudio: 'High-quality video and audio',
    screenSharing: 'Screen sharing for medical reports',
    callRecording: 'Recording for medical records',
    secureHipaaCompliant: 'Secure, HIPAA-compliant platform',

    // Medicines
    medicineAvailability: 'Medicine Availability',
    searchMedicine: 'Search medicine name...',
    popularMedicines: 'Popular Medicines',
    medicineAvailable: 'Medicine Available!',
    outOfStock: 'Out of Stock',
    medicineNotFound: 'Medicine Not Found',
    yourPrescriptions: 'Your Prescriptions',
    markAsTaken: 'Mark as Taken',

    // Pharmacy
    totalMedicines: 'Total Medicines',
    lowStock: 'Low Stock',
    needRestocking: 'Need restocking',
    urgentRestocking: 'Urgent restocking',
    monthlySales: 'Monthly Sales',
    addNewMedicine: 'Add New Medicine',
    updateInventory: 'Update Inventory',
    lowStockAlert: 'Low Stock Alert',
    medicineInventory: 'Medicine Inventory',
    medicineName: 'Medicine Name',
    stock: 'Stock',
    price: 'Price',
    manufacturer: 'Manufacturer',
    status: 'Status',
    actions: 'Actions',
    inStock: 'In Stock',
    stockQuantity: 'Stock Quantity',
    pricePerUnit: 'Price per Unit',
    expiryDate: 'Expiry Date',
    addToInventory: 'Add Medicine to Inventory',
    medicineRequests: 'Medicine Requests',
    patientQueries: 'Patient queries about medicine availability',
    available: 'Available',
    contactPatient: 'Contact Patient',
    suggestAlternative: 'Suggest Alternative',


    activePatients: 'Active Patients',
    activeDoctors: 'Active Doctors',
    partnerPharmacies: 'Partner Pharmacies',
    totalConsultations: 'Total Consultations',
    userManagement: 'User Management',
    manageUsers: 'Manage all platform users',
    platformGrowth: 'Platform Growth',
    revenueAnalytics: 'Revenue Analytics',
    generateReports: 'Generate Reports',
    exportData: 'Export platform data and analytics',
    userReport: 'User Report',
    analyticsReport: 'Analytics Report',
    consultationReport: 'Consultation Report',
    systemAlerts: 'System Alerts',
    systemHealth: 'System Health',

    // Common
    search: 'Search',
    filter: 'Filter',
    save: 'Save',
    cancel: 'Cancel',
    submit: 'Submit',
    loading: 'Loading...',
    name: 'Name',
    location: 'Location',
    phone: 'Phone',
    date: 'Date',
    time: 'Time',
    notes: 'Notes',
    patient: 'Patient',
    doctor: 'Doctor',
    pharmacy: 'Pharmacy',

    active: 'Active',
    inactive: 'Inactive',
    emergency: 'Emergency',
    settings: 'Settings',
    theme: 'Theme',
    language: 'Language',
    lightMode: 'Light Mode',
    darkMode: 'Dark Mode',
    systemMode: 'System Mode',
  },
  ta: {
  loginHeadline: 'மக்கள் நலத்திற்காக கிராமப்புறங்களை இணைக்கும்',
  loginSubheadline: 'எங்கள் விரிவான டெலிமெடிசின் தளத்துடன் சுகாதார இடைவெளியை குறைக்கவும். உங்கள் கிராமத்திலிருந்தே நிபுணர் ஆலோசனைகள், டிஜிட்டல் மருந்து பரிந்துரைகள் மற்றும் மருந்து கிடைப்பை சரிபார்க்கவும்.',
  loginFeatureConsult: 'வீடியோ/ஆடியோ ஆலோசனைகள்',
  loginFeatureDelivery: 'மருந்துகள் டெலிவரி',
  loginFeatureSupport: '24/7 ஆதரவு',
  loginStatPatients: '1,250+ செயலில் உள்ள நோயாளிகள்',
  loginStatDoctors: '45+ தகுதியான மருத்தவர்கள்',
  loginStatPharmacies: '18+ கூட்டணி மருந்தகங்கள்',
  loginStatSuccess: '97.5% வெற்றிகரமான விகிதம்',
  loginTrusted: 'மருத்துவ நிபுணர்களால் நம்பிக்கை',
  loginCompliance: 'HIPAA இணக்கம்',
  loginEncryption: 'முழுமையான குறியாக்கம்',
  loginMonitoring: '24/7 கண்காணிப்பு',
  loginSignInTitle: 'TeleAsha-வில் உள்நுழையவும்',
  loginDashboardAccess: 'உங்கள் சுகாதார டாஷ்போர்டை அணுகவும்',
  loginEmail: 'மின்னஞ்சல்',
  loginPassword: 'கடவுச்சொல்',
  loginSignInButton: 'உள்நுழைய',
  loginNewTo: 'TeleAsha-வில் புதியவரா?',
  loginCreateAccount: 'புதிய கணக்கு உருவாக்கவும்',
  loginAgreement: 'உள்நுழைவதன் மூலம், நீங்கள் எங்கள் சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்கின்றீர்கள்',
    // Navigation
    dashboard: 'டாஷ்போர்டு',
    appointments: 'சந்திப்புகள்',
    medicines: 'மருந்துகள்',
    reports: 'அறிக்கைகள்',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    overview: 'மேலோட்டம்',
  symptomsNav: 'அறிகுறி சரிபார்ப்பு',
    consultations: 'ஆலோசனைகள்',
    prescriptions: 'மருந்து பரிந்துரைகள்',
    inventory: 'சரக்கு',
    addMedicine: 'மருந்து சேர்க்க',
    requests: 'கோரிக்கைகள்',
    users: 'பயனர்கள்',
    analytics: 'பகுப்பாய்வு',

    // Authentication
    login: 'உள்நுழைய',
    register: 'பதிவு செய்ய',
    forgotPassword: 'கடவுச்சொல்லை மறந்துவிட்டீர்களா',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    confirmPassword: 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    fullName: 'முழு பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    signIn: 'உள்நுழைய',
    signingIn: 'உள்நுழைகிறது...',
    demoAccess: 'டெமோ அணுகல்',
    demoPassword: 'அனைத்து கணக்குகளுக்கும் டெமோ கடவுச்சொல்',

    // Dashboard
    welcome: 'வரவேற்கிறோம்',
    upcomingAppointments: 'வரவிருக்கும் சந்திப்புகள்',
    recentReports: 'சமீபத்திய அறிக்கைகள்',
    bookConsultation: 'ஆலோசனை பதிவு செய்யுங்கள்',
    bookAppointment: 'சந்திப்பு பதிவு செய்யுங்கள்',
    checkMedicine: 'மருந்து சரிபார்க்கவும்',
    videoAudioCall: 'வீடியோ/ஆடியோ அழைப்பு',
    findPharmacy: 'மருந்தகம் கண்டறியவும்',
    healthScore: 'உடல்நலம் மதிப்பெண்',
    activePrescriptions: 'செயலில் உள்ள பரிந்துரைகள்',
    quickActions: 'விரைவு செயல்கள்',
    recentActivity: 'சமீபத்திய செயல்பாடு',

    // Doctor types
    modernMedicine: 'நவீன மருத்துவம்',
    countryMedicine: 'நாட்டு மருத்துவம்',
    generalMedicine: 'பொது மருத்துவம்',

    // Medical
  symptoms: 'அறிகுறிகள்',
    fever: 'காய்ச்சல்',
    cough: 'இருமல்',
    headache: 'தலைவலி',
    bodyPain: 'உடல் வலி',
    nausea: 'குமட்டல்',
    fatigue: 'சோர்வு',
    otherSymptoms: 'மற்ற அறிகுறிகள்',
    checkSymptoms: 'அறிகுறிகளை சரிபார்க்கவும்',
    symptomsRecorded: 'அறிகுறிகள் பதிவு செய்யப்பட்டன',
    consultDoctor: 'உங்கள் அறிகுறிகளின் அடிப்படையில், மருத்துவரை அணுக பரிந்துரைக்கிறோம். சந்திப்பு பதிவு செய்ய விரும்புகிறீர்களா?',

    // Common
    search: 'தேடு',
    filter: 'வடிகட்டி',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    submit: 'சமர்ப்பி',
    loading: 'ஏற்றுகிறது...',
    name: 'பெயர்',
    location: 'இடம்',
    phone: 'தொலைபேசி',
    date: 'தேதி',
    time: 'நேரம்',
    notes: 'குறிப்புகள்',
    patient: 'நோயாளி',
    doctor: 'மருத்துவர்',
    pharmacy: 'மருந்தகம்',

    active: 'செயலில்',
    inactive: 'செயலில் இல்லை',
    emergency: 'அவசரம்',
    settings: 'அமைப்புகள்',
    theme: 'தீம்',
    language: 'மொழி',
    lightMode: 'ஒளி பயன்முறை',
    darkMode: 'இருள் பயன்முறை',
    systemMode: 'கணினி பயன்முறை',
  },
  hi: {
  loginHeadline: 'ग्रामीण समुदायों को गुणवत्तापूर्ण स्वास्थ्यसेவाओं से जोड़ना',
  loginSubheadline: 'हमारे व्यापक टेलीमेडिसिन प्लेटफ़ॉर्म के साथ स्वास्थ्य देखभाल की खाई को पाटें। अपने गाँव से विशेषज्ञ परामर्श, डिजिटल नुस्खे और दवा उपलब्धता जांचें।',
  loginFeatureConsult: 'वीडियो/ऑडियो परामर्श',
  loginFeatureDelivery: 'दवाइयों की डिलीवरी',
  loginFeatureSupport: '24/7 सहायता',
  loginStatPatients: '1,250+ सक्रिय मरीज',
  loginStatDoctors: '45+ योग्य डॉक्टर',
  loginStatPharmacies: '18+ साझेदार फार्मेसियाँ',
  loginStatSuccess: '97.5% सफलता दर',
  loginTrusted: 'स्वास्थ्य पेशेवरों द्वारा विश्वसनीय',
  loginCompliance: 'HIPAA अनुरूप',
  loginEncryption: 'एंड-टू-एंड एन्क्रिप्टेड',
  loginMonitoring: '24/7 निगरानी',
  loginSignInTitle: 'TeleAsha में अपने खाते में साइन इन करें',
  loginDashboardAccess: 'अपने स्वास्थ्य डैशबोर्ड तक पहुँचें',
  loginEmail: 'ईमेल',
  loginPassword: 'पासवर्ड',
  loginSignInButton: 'साइन इन करें',
  loginNewTo: 'TeleAsha में नए हैं?',
  loginCreateAccount: 'नया खाता बनाएँ',
  loginAgreement: 'साइन इन करके, आप हमारी सेवा की शर्तों और गोपनीयता नीति से सहमत होते हैं',
    // Navigation
    dashboard: 'डैशबोर्ड',
    appointments: 'अपॉइंटमेंट्स',
    medicines: 'दवाइयां',
    reports: 'रिपोर्ट्स',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    overview: 'अवलोकन',
  symptomsNav: 'लक्षण जांचकर्ता',
    consultations: 'परामर्श',
    prescriptions: 'नुस्खे',
    inventory: 'इन्वेंटरी',
    addMedicine: 'दवा जोड़ें',
    requests: 'अनुरोध',
    users: 'उपयोगकर्ता',
    analytics: 'विश्लेषण',

    // Authentication
    login: 'लॉगिन',
    register: 'रजिस्टर',
    forgotPassword: 'पासवर्ड भूल गए',
    email: 'ईमेल',
    password: 'पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    fullName: 'पूरा नाम',
    phoneNumber: 'फोन नंबर',
    signIn: 'साइन इन',
    signingIn: 'साइन इन हो रहा है...',
    demoAccess: 'डेमो एक्सेस',
    demoPassword: 'सभी खातों के लिए डेमो पासवर्ड',

    // Dashboard
    welcome: 'स्वागत है',
    upcomingAppointments: 'आगामी अपॉइंटमेंट्स',
    recentReports: 'हाल की रिपोर्ट्स',
    bookConsultation: 'परामर्श बुक करें',
    bookAppointment: 'अपॉइंटमेंट बुक करें',
    checkMedicine: 'दवा जांचें',
    videoAudioCall: 'वीडियो/ऑडियो कॉल',
    findPharmacy: 'फार्मेसी खोजें',
    healthScore: 'स्वास्थ्य स्कोर',
    activePrescriptions: 'सक्रिय नुस्खे',
    quickActions: 'त्वरित कार्य',
    recentActivity: 'हाल की गतिविधि',

    // Doctor types
    modernMedicine: 'आधुनिक चिकित्सा',
    countryMedicine: 'देशी चिकित्सा',
    generalMedicine: 'सामान्य चिकित्सा',

    // Medical
  symptoms: 'लक्षण',
    fever: 'बुखार',
    cough: 'खांसी',
    headache: 'सिरदर्द',
    bodyPain: 'शरीर में दर्द',
    nausea: 'मतली',
    fatigue: 'थकान',
    otherSymptoms: 'अन्य लक्षण',
    checkSymptoms: 'लक्षण जांचें',
    symptomsRecorded: 'लक्षण दर्ज किए गए',
    consultDoctor: 'आपके लक्षणों के आधार पर, हम डॉक्टर से सलाह लेने की सिफारिश करते हैं। क्या आप अपॉइंटमेंट बुक करना चाहते हैं?',

    // Common
    search: 'खोजें',
    filter: 'फिल्टर',
    save: 'सेव करें',
    cancel: 'रद्द करें',
    submit: 'सबमिट करें',
    loading: 'लोड हो रहा है...',
    name: 'नाम',
    location: 'स्थान',
    phone: 'फोन',
    date: 'तारीख',
    time: 'समय',
    notes: 'नोट्स',
    patient: 'मरीज़',
    doctor: 'डॉक्टर',
    pharmacy: 'फार्मेसी',

    active: 'सक्रिय',
    inactive: 'निष्क्रिय',
    emergency: 'आपातकाल',
    settings: 'सेटिंग्स',
    theme: 'थीम',
    language: 'भाषा',
    lightMode: 'लाइट मोड',
    darkMode: 'डार्क मोड',
    systemMode: 'सिस्टम मोड',
  },
  gu: {
  loginHeadline: 'ગ્રામ્ય સમુદાયોને ગુણવત્તાવાળી આરોગ્યસેવામાં જોડવું',
  loginSubheadline: 'અમારા વ્યાપક ટેલિમેડિસિન પ્લેટફોર્મ સાથે આરોગ્યની ખોટ પૂરી કરો. તમારા ગામમાંથી નિષ્ણાત સલાહ, ડિજિટલ પ્રિસ્ક્રિપ્શન અને દવા ઉપલબ્ધિ તપાસો.',
  loginFeatureConsult: 'વિડિયો/ઓડિયો સલાહ',
  loginFeatureDelivery: 'દવાઓ ડિલિવરી',
  loginFeatureSupport: '24/7 સપોર્ટ',
  loginStatPatients: '1,250+ સક્રિય દર્દીઓ',
  loginStatDoctors: '45+ લાયક ડૉક્ટરો',
  loginStatPharmacies: '18+ પાર્ટનર ફાર્મસી',
  loginStatSuccess: '97.5% સફળતા દર',
  loginTrusted: 'હેલ્થકેર પ્રોફેશનલ્સ દ્વારા વિશ્વસનીય',
  loginCompliance: 'HIPAA અનુરૂપ',
  loginEncryption: 'એન્ડ-ટુ-એન્ડ એન્ક્રિપ્ટેડ',
  loginMonitoring: '24/7 મોનિટરિંગ',
  loginSignInTitle: 'TeleAsha માટે તમારા ખાતામાં સાઇન ઇન કરો',
  loginDashboardAccess: 'તમારા આરોગ્ય ડેશબોર્ડને ઍક્સેસ કરો',
  loginEmail: 'ઇમેઇલ',
  loginPassword: 'પાસવર્ડ',
  loginSignInButton: 'સાઇન ઇન કરો',
  loginNewTo: 'TeleAsha માટે નવા છો?',
  loginCreateAccount: 'નવું ખાતું બનાવો',
  loginAgreement: 'સાઇન ઇન કરીને, તમે અમારી સેવા શરતો અને ગોપનીયતા નીતિથી સંમત છો',
    // Navigation
    dashboard: 'ડેશબોર્ડ',
    appointments: 'મુલાકાતો',
    medicines: 'દવાઓ',
    reports: 'રિપોર્ટ્સ',
    profile: 'પ્રોફાઇલ',
    logout: 'લૉગઆઉટ',
    overview: 'ઝાંખી',
  symptomsNav: 'લક્ષણ તપાસનાર',
    consultations: 'સલાહ',
    prescriptions: 'પ્રિસ્ક્રિપ્શન',
    inventory: 'ઇન્વેન્ટરી',
    addMedicine: 'દવા ઉમેરો',
    requests: 'વિનંતીઓ',
    users: 'વપરાશકર્તાઓ',
    analytics: 'વિશ્લેષણ',

    // Authentication
    login: 'લૉગિન',
    register: 'નોંધણી',
    forgotPassword: 'પાસવર્ડ ભૂલી ગયા',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    confirmPassword: 'પાસવર્ડની પુષ્ટિ કરો',
    fullName: 'પૂરું નામ',
    phoneNumber: 'ફોન નંબર',
    signIn: 'સાઇન ઇન',
    signingIn: 'સાઇન ઇન થઈ રહ્યું છે...',
    demoAccess: 'ડેમો એક્સેસ',
    demoPassword: 'બધા એકાઉન્ટ્સ માટે ડેમો પાસવર્ડ',

    // Dashboard
    welcome: 'સ્વાગત છે',
    upcomingAppointments: 'આગામી મુલાકાતો',
    recentReports: 'તાજેતરની રિપોર્ટ્સ',
    bookConsultation: 'સલાહ બુક કરો',
    bookAppointment: 'મુલાકાત બુક કરો',
    checkMedicine: 'દવા તપાસો',
    videoAudioCall: 'વિડિયો/ઓડિયો કૉલ',
    findPharmacy: 'ફાર્મસી શોધો',
    healthScore: 'આરોગ્ય સ્કોર',
    activePrescriptions: 'સક્રિય પ્રિસ્ક્રિપ્શન',
    quickActions: 'ઝડપી ક્રિયાઓ',
    recentActivity: 'તાજેતરની પ્રવૃત્તિ',

    // Doctor types
    modernMedicine: 'આધુનિક દવા',
    countryMedicine: 'દેશી દવા',
    generalMedicine: 'સામાન્ય દવા',

    // Medical
  symptoms: 'લક્ષણો',
    fever: 'તાવ',
    cough: 'ઉધરસ',
    headache: 'માથાનો દુખાવો',
    bodyPain: 'શરીરનો દુખાવો',
    nausea: 'ઉબકા',
    fatigue: 'થાક',
    otherSymptoms: 'અન્ય લક્ષણો',
    checkSymptoms: 'લક્ષણો તપાસો',
    symptomsRecorded: 'લક્ષણો નોંધાયા',
    consultDoctor: 'તમારા લક્ષણોના આધારે, અમે ડૉક્ટરની સલાહ લેવાની ભલામણ કરીએ છીએ. શું તમે મુલાકાત બુક કરવા માંગો છો?',

    // Common
    search: 'શોધો',
    filter: 'ફિલ્ટર',
    save: 'સેવ કરો',
    cancel: 'રદ કરો',
    submit: 'સબમિટ કરો',
    loading: 'લોડ થઈ રહ્યું છે...',
    name: 'નામ',
    location: 'સ્થાન',
    phone: 'ફોન',
    date: 'તારીખ',
    time: 'સમય',
    notes: 'નોંધો',
    patient: 'દર્દી',
    doctor: 'ડૉક્ટર',
    pharmacy: 'ફાર્મસી',

    active: 'સક્રિય',
    inactive: 'નિષ્ક્રિય',
    emergency: 'કટોકટી',
    settings: 'સેટિંગ્સ',
    theme: 'થીમ',
    language: 'ભાષા',
    lightMode: 'લાઇટ મોડ',
    darkMode: 'ડાર્ક મોડ',
    systemMode: 'સિસ્ટમ મોડ',
  },
  pa: {
  loginHeadline: 'ਪਿੰਡਾਂ ਨੂੰ ਗੁਣਵੱਤਾ ਵਾਲੀ ਸਿਹਤ ਸੇਵਾ ਨਾਲ ਜੋੜਨਾ',
  loginSubheadline: 'ਸਾਡਾ ਵਿਸ਼ਤ੍ਰਿਤ ਟੈਲੀਮੇਡੀਸਿਨ ਪਲੇਟਫਾਰਮ ਨਾਲ ਸਿਹਤ ਦੀ ਖਾਈ ਪੂਰੀ ਕਰੋ। ਆਪਣੇ ਪਿੰਡ ਤੋਂ ਨਿਪੁੰਨ ਸਲਾਹ, ਡਿਜ਼ੀਟਲ ਨੁਸਖੇ ਅਤੇ ਦਵਾਈ ਉਪਲਬਧਤਾ ਚੈੱਕ ਕਰੋ।',
  loginFeatureConsult: 'ਵੀਡੀਓ/ਆਡੀਓ ਸਲਾਹ',
  loginFeatureDelivery: 'ਦਵਾਈਆਂ ਡਿਲਿਵਰੀ',
  loginFeatureSupport: '24/7 ਸਹਾਇਤਾ',
  loginStatPatients: '1,250+ ਸਰਗਰਮ ਮਰੀਜ਼',
  loginStatDoctors: '45+ ਯੋਗ ਡਾਕਟਰ',
  loginStatPharmacies: '18+ ਭਾਗੀਦਾਰ ਫਾਰਮੇਸੀ',
  loginStatSuccess: '97.5% ਸਫਲਤਾ ਦਰ',
  loginTrusted: 'ਹੈਲਥਕੇਅਰ ਪੇਸ਼ੇਵਰਾਂ ਵੱਲੋਂ ਭਰੋਸੇਯੋਗ',
  loginCompliance: 'HIPAA ਅਨੁਕੂਲ',
  loginEncryption: 'ਐਂਡ-ਟੂ-ਐਂਡ ਇੰਕ੍ਰਿਪਟਡ',
  loginMonitoring: '24/7 ਨਿਗਰਾਨੀ',
  loginSignInTitle: 'TeleAsha ਲਈ ਆਪਣੇ ਖਾਤੇ ਵਿੱਚ ਸਾਈਨ ਇਨ ਕਰੋ',
  loginDashboardAccess: 'ਆਪਣੇ ਸਿਹਤ ਡੈਸ਼ਬੋਰਡ ਤੱਕ ਪਹੁੰਚੋ',
  loginEmail: 'ਈਮੇਲ',
  loginPassword: 'ਪਾਸਵਰਡ',
  loginSignInButton: 'ਸਾਈਨ ਇਨ ਕਰੋ',
  loginNewTo: 'TeleAsha ਲਈ ਨਵੇਂ ਹੋ?',
  loginCreateAccount: 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
  loginAgreement: 'ਸਾਈਨ ਇਨ ਕਰਕੇ, ਤੁਸੀਂ ਸਾਡੀਆਂ ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ ਅਤੇ ਪਰਦੇਦਾਰੀ ਨੀਤੀ ਨਾਲ ਸਹਿਮਤ ਹੋ',
    // Navigation
    dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    appointments: 'ਮੁਲਾਕਾਤਾਂ',
    medicines: 'ਦਵਾਈਆਂ',
    reports: 'ਰਿਪੋਰਟਾਂ',
    profile: 'ਪ੍ਰੋਫ਼ਾਈਲ',
    logout: 'ਲੌਗਆਉਟ',
    overview: 'ਸੰਖੇਪ',
  symptomsNav: 'ਲੱਛਣ',
  symptoms: 'ਲੱਛਣ',
    consultations: 'ਸਲਾਹ',
    prescriptions: 'ਨੁਸਖੇ',
    inventory: 'ਇਨਵੈਂਟਰੀ',
    addMedicine: 'ਦਵਾਈ ਸ਼ਾਮਲ ਕਰੋ',
    requests: 'ਬੇਨਤੀਆਂ',
    users: 'ਉਪਭੋਗਤਾ',
    analytics: 'ਵਿਸ਼ਲੇਸ਼ਣ',

    // Authentication
    login: 'ਲੌਗਇਨ',
    register: 'ਰਜਿਸਟਰ',
    forgotPassword: 'ਪਾਸਵਰਡ ਭੁੱਲ ਗਏ',
    email: 'ਈਮੇਲ',
    password: 'ਪਾਸਵਰਡ',
    confirmPassword: 'ਪਾਸਵਰਡ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ',
    fullName: 'ਪੂਰਾ ਨਾਮ',
    phoneNumber: 'ਫ਼ੋਨ ਨੰਬਰ',
    signIn: 'ਸਾਈਨ ਇਨ',
    signingIn: 'ਸਾਈਨ ਇਨ ਹੋ ਰਿਹਾ ਹੈ...',
    demoAccess: 'ਡੈਮੋ ਐਕਸੈਸ',
    demoPassword: 'ਸਭ ਖਾਤਿਆਂ ਲਈ ਡੈਮੋ ਪਾਸਵਰਡ',

    // Dashboard
    welcome: 'ਜੀ ਆਇਆਂ ਨੂੰ',
    upcomingAppointments: 'ਆਉਣ ਵਾਲੀਆਂ ਮੁਲਾਕਾਤਾਂ',
    recentReports: 'ਤਾਜ਼ਾ ਰਿਪੋਰਟਾਂ',
    bookConsultation: 'ਸਲਾਹ ਬੁੱਕ ਕਰੋ',
    bookAppointment: 'ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰੋ',
    checkMedicine: 'ਦਵਾਈ ਚੈੱਕ ਕਰੋ',
    videoAudioCall: 'ਵੀਡੀਓ/ਆਡੀਓ ਕਾਲ',
    findPharmacy: 'ਫਾਰਮੇਸੀ ਲੱਭੋ',
    healthScore: 'ਸਿਹਤ ਸਕੋਰ',
    activePrescriptions: 'ਸਕਰੀਅ ਨੁਸਖੇ',
    quickActions: 'ਤੁਰੰਤ ਕਾਰਵਾਈ',
    recentActivity: 'ਤਾਜ਼ਾ ਸਰਗਰਮੀ',

    // Doctor types
    modernMedicine: 'ਆਧੁਨਿਕ ਦਵਾਈ',
    countryMedicine: 'ਦੇਸੀ ਦਵਾਈ',
    generalMedicine: 'ਆਮ ਦਵਾਈ',

    // Medical
    fever: 'ਬੁਖਾਰ',
    cough: 'ਖੰਘ',
    headache: 'ਸਿਰ ਦਰਦ',
    bodyPain: 'ਸਰੀਰ ਦਰਦ',
    nausea: 'ਉਲਟੀ',
    fatigue: 'ਥਕਾਵਟ',
    otherSymptoms: 'ਹੋਰ ਲੱਛਣ',
    checkSymptoms: 'ਲੱਛਣ ਚੈੱਕ ਕਰੋ',
    symptomsRecorded: 'ਲੱਛਣ ਦਰਜ ਹੋਏ',
    consultDoctor: 'ਤੁਹਾਡੇ ਲੱਛਣਾਂ ਦੇ ਆਧਾਰ ਤੇ, ਅਸੀਂ ਡਾਕਟਰ ਦੀ ਸਲਾਹ ਲੈਣ ਦੀ ਸਿਫਾਰਸ਼ ਕਰਦੇ ਹਾਂ। ਕੀ ਤੁਸੀਂ ਮੁਲਾਕਾਤ ਬੁੱਕ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?',

    // Common
    search: 'ਖੋਜੋ',
    filter: 'ਫਿਲਟਰ',
    save: 'ਸੇਵ ਕਰੋ',
    cancel: 'ਰੱਦ ਕਰੋ',
    submit: 'ਸਬਮਿਟ ਕਰੋ',
    loading: 'ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...',
    name: 'ਨਾਮ',
    location: 'ਟਿਕਾਣਾ',
    phone: 'ਫ਼ੋਨ',
    date: 'ਤਾਰੀਖ',
    time: 'ਸਮਾਂ',
    notes: 'ਨੋਟਸ',
    patient: 'ਮਰੀਜ਼',
    doctor: 'ਡਾਕਟਰ',
    pharmacy: 'ਫਾਰਮੇਸੀ',

    active: 'ਸਕਰੀਅ',
    inactive: 'ਨਿਸ਼ਕਰੀਅ',
    emergency: 'ਐਮਰਜੈਂਸੀ',
    settings: 'ਸੈਟਿੰਗ',
    theme: 'ਥੀਮ',
    language: 'ਭਾਸ਼ਾ',
    lightMode: 'ਲਾਈਟ ਮੋਡ',
    darkMode: 'ਡਾਰਕ ਮੋਡ',
    systemMode: 'ਸਿਸਟਮ ਮੋਡ',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'en';
  });

  const setLanguage = (language: string) => {
    setCurrentLanguage(language);
    localStorage.setItem('language', language);
  };

  const t = (key: string): string => {
    const translation = translations[currentLanguage as keyof typeof translations];
    return translation?.[key as keyof typeof translation] || key;
  };

  useEffect(() => {
    // Set document direction for RTL languages if needed
    document.documentElement.dir = currentLanguage === 'ar' ? 'rtl' : 'ltr';
  }, [currentLanguage]);

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        availableLanguages: languages,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
    return context;
  };